version: '3.8'

services:
  backend:
    image: otapiero/notes-backend:latest
    container_name: notes-backend-hub
    ports:
      - "5000:5000"
    networks:
      - app-network

  frontend:
    image: otapiero/notes-frontend:latest
    container_name: notes-frontend-hub
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
